name: Smol Researcher

on:
  issue_comment:
    types: [created]

jobs:
  research:
    if: contains(github.event.comment.body, '@smol_researcher')
    runs-on: ubuntu-latest
    env:
      LLM_MODEL: ${{ vars.LLM_MODEL }}
      LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install smolagents
          pip install beautifulsoup4
          pip install requests
          pip install litellm

      - name: Prepare input
        run: |
          comment_body=$(echo "${{ github.event.comment.body }}" | sed 's/@smol_researcher//')
          echo "User request: $comment_body" > input.txt
          echo "Issue context:" >> input.txt
          echo "Title: ${{ github.event.issue.title }}" >> input.txt
          echo "Body: ${{ github.event.issue.body }}" >> input.txt

      - name: Run research script
        run: |
          mkdir -p scripts
          python scripts/research_agent.py --input input.txt --output input.txt

      - name: Post result as comment
        run: |
          if [ -s output.txt ]; then
            output=$(cat output.txt)
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -d "{\"body\": \"Smol Researcher Result:\n\n$output\"}" \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"
          else
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -d "{\"body\": \"Unable to process the request at this time.\"}" \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"
          fi
